[package]
name = "sliced"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custos = {path = "../custos", default-features=false, features=["opencl", "stack", "macro", "blas", "cpu", "autograd"]}

[features]
default = ["stack", "cpu", "opencl", "blas"]
autograd = []
stack = []
cpu = []
opencl = []
blas = []

[dev-dependencies]
rawsliced = { path = "../rawsliced" }