[package]
name = "sliced"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custos = {path = "../custos", default-features=false, features=["opencl", "stack", "macro", "blas", "cpu", "autograd"]}
fastrand = "1.8.0"

[features]
default = ["stack", "cpu", "opencl", "blas", "matrix", "autograd"]
autograd = ["custos/autograd"]
stack = []
cpu = []
opencl = []
blas = []
matrix = []

[dev-dependencies]
rawsliced = { path = "../rawsliced" }
graplot = "0.1.22"
